baseURL = "/"
languageCode = "en-us"
title = "KFA - Kayak Fishing Association of New York"
canonifyurls = true
relativeURLs = true

[[menu.sidebar]]
name = "About"
url = "/about"
weight = 1

[[menu.sidebar]]
name = "Forum"
url = "http://kfa-ny.org/forum"
weight = 2

[[menu.sidebar]]
name = "Join Us"
url = "/join"
weight = 2